### ISSUE TITLE
Change NeoVim -> Neovim

### ISSUE THREAD

**Issue by jdavis** [rogual/neovim-dot-app#10]
Just an issue for what I mentioned in [this tweet](https://twitter.com/HopefulJosh/status/581171148420833280).

The [upcoming newsletter](https://github.com/neovim/neovim.github.io/pull/82) is coming out next weekend and I plan on featuring this project in one of the sections =]

**Comment by rogual** [comment]
Done! https://github.com/rogual/neovim-dot-app/commit/ad5e6ea7b89390e4d6eb28a2176efac00f9a5e79

**Comment by Pyrohh** [comment]
It looks like you missed just one:

![lel_crop](https://cloud.githubusercontent.com/assets/4174345/6913070/d684b26e-d748-11e4-9d6b-37f0054f92f2.png)

**Comment by rogual** [comment]
D'oh! Cheers.
