### ISSUE TITLE
Independent of showcmd some textobjects fail

### ISSUE THREAD

**Issue by khalidchawtany** [rogual/neovim-dot-app#135]
When I press **ciw** on a word the cursor jumps to the next word (as if only **w** was pressed ).
This does not happen in **terminal nvim** and it is independent of **showcmd** state. I tried with both of **showcmd**, **noshowcmd** and the result was the same. This happens with **argumentative** and other plugins (See the note below) n combination with a mapping that begins with character **c** + ? (vim-unimpared is full of this kind of mappings). 

**Minimal nvimrc**
```vim
nnoremap coo :echo "Text"<cr>
call plug#begin('~/.nvim/plugged')
  Plug 'PeterRincker/vim-argumentative'
call plug#end()

```

**Environment:**
```
OS X 10.10.5
```
**nvim version:** from neovim-dot-app *:verison* output.
```
NVIM 0.0.0-alpha+201509190915 (compiled Sep 20 2015 19:25:58)
Commit: 2417aeebbffe58eab6ac39feac0f64a27aafbee2
Build type: RelWithDebInfo

```

**Note:**
I tried to find other plugins that are causing this issue using binary search. However, I could not find them, as more than one plugin come together to produce this bug. Except for **argumentative** which can cause it alone. 
As a workaround, I have written a little function to ```unmap``` all mappings that begin with letter **c**.

**Comment by bambu** [comment]
@khalidchawtany 
I could not get get this to reproduce. I have yet to try `argumentative` and will try it later on today. 

Does the same problem exist if you run Neovim without any plugins/settings?
```
/Applications/Neovim.app/Contents/MacOS/Neovim -u NONE
```

**Comment by khalidchawtany** [comment]
This does not happen with an empty **nvimrc**. It even does not happen if I *unmap* all mappings that begin with **c** with all my plugins enabled (Which, I have a lot of).

The problem is, this does not happen in **terminal nvim**.

**Comment by rogual** [comment]
I suspect this is the same issue as https://github.com/rogual/neovim-dot-app/issues/112 — caused by a change to how Neovim's API works internally. Either their change introduced a bug, or my code uses their API wrong.

What we really need is a reproducible minimal test case for that bug, which is something I haven't had time to look into lately. Annoying, I know.

**Comment by khalidchawtany** [comment]
I will try to breakdown **argumentative** plugin to see what might be causing it, although I know very little about **vimscript** :(

**Comment by khalidchawtany** [comment]
@rogual here is a **minimal nvimrc** to reproduce the bug:

```
omap i, :echo "Something"<cr>
nnoremap coo :echo "Text"<cr>
```

**Comment by bambu** [comment]
This is defnitely attributed to the update that neovim did. Going back to neovim's `e1f83d3` makes `ciw` work even with `argumentative`. It fails with commit `ccdeb91` and newer. 

Tried to replicate the issue via lua as was mentioned in the vim_input issue and was not able to reproduce it. I also tried to reproduce in Neovim, the nvim command the way that busted calls it and the problem still persists after setting up @khalidchawtany minimized mappings.  

The lua script that i wrote based on the sample one in the the `vim_input` issue is:

```diff
diff --git a/test/functional/ui/input_spec.lua b/test/functional/ui/input_spec.lua
index 81af908..39475fa 100644
--- a/test/functional/ui/input_spec.lua
+++ b/test/functional/ui/input_spec.lua
@@ -1,5 +1,6 @@
 local helpers = require('test.functional.helpers')
 local clear, execute, nvim = helpers.clear, helpers.execute, helpers.nvim
+local Screen = require('test.functional.ui.screen')
 local feed, next_message, eq = helpers.feed, helpers.next_message, helpers.eq
 local expect = helpers.expect
 
@@ -38,9 +39,38 @@ describe('mappings', function()
     check_mapping('<a-c-s-up>', '<c-s-a-up>')
     check_mapping('<a-s-c-up>', '<c-s-a-up>')
   end)
+
+  describe('with showcmd', function()
+    it('ok', function()
+      local screen = Screen.new()
+      screen:attach()
+      feed('iapple(green, blue)<esc>')
+      feed(':omap i, :echo "Something"<cr>')
+      feed(':nnoremap coo :echo "Text"<cr>')
+      feed('^ciw<esc>')
+      screen:snapshot_util({}, true)
+      screen:expect([[
+        ^(green, blue)                                        |
+        ~                                                    |
+        ~                                                    |
+        ~                                                    |
+        ~                                                    |
+        ~                                                    |
+        ~                                                    |
+        ~                                                    |
+        ~                                                    |
+        ~                                                    |
+        ~                                                    |
+        ~                                                    |
+        ~                                                    |
+                                                             |
+      ]])
+    end)
+  end)
 end)
 
 describe('input utf sequences that contain CSI/K_SPECIAL', function()
+  before_each(clear)
   it('ok', function()
     feed('i…<esc>')
     expect('…')
````

This passed. Though in Neovim this process of setting the mapping and typing ciw failed. The failure result in theory should have displayed:
```
         apple^(green, blue)                                        |
```

**Comment by khalidchawtany** [comment]
Could this be related to [this bug](https://github.com/neovim/neovim/issues/3382) reported in **neovim**?
@bambu  @rogual

**Comment by bambu** [comment]
The fix for that issue will be the root solution for this issue

**Comment by rogual** [comment]
Many thanks guys. Guess I'd better get #123 merged.

Link to other neovim issue for convenience: https://github.com/neovim/neovim/issues/3282

**Comment by rogual** [comment]
I've merged #123. Can you reproduce this issue on current master @khalidchawtany ?

**Comment by khalidchawtany** [comment]
Unfortunately its not solved. I just tried with the minimal nvimrc presented above and I still cannot use *ciw**.

**Comment by khalidchawtany** [comment]
I just did a reinstall of **nvim** followed by a reinstall of **neovim-dot-app** and everything is working :+1: 

Thank you very much :)
