### ISSUE TITLE
Colour space differs from MacVim and Terminal

### ISSUE THREAD

**Issue by kopischke** [rogual/neovim-dot-app#50]
_Neovim.app_’s colour space does not match that of other GUI apps, the resultant effect with a light, mid contrast theme like _Solarized light_ being a washed out look. In the screenshot below, the right hand window is _MacVim_. Its colour space corresponds to that used by _Terminal.app_ when configured to use Solarized as ANSI colours. The left hand window is Neovim.app, using the same config and colour theme, looking distinctly lighter:

![Neovim.app vs. MacVim](https://cloud.githubusercontent.com/assets/80906/7048704/deffe026-de14-11e4-88ab-7cfb0da6bfc6.png)

For reference, colour code for the light background:
- Screen rendering of MacVim and Terminal.app: `#fef7e3`
- Screen rendering of Neovim.app: `#fef7e8`

(note none of these exactly matches the [Solarized Base3 colour definition](http://ethanschoonover.com/solarized) of `#fdf6e3` – the point here is not that OS X colour rendering has its quirks, but that Neovim.app deviates from the otherwise, er, consistently quirky behaviour).

_Neovim.app 814cf2bd7ee3f26dde65a2e9eff1396ebc5205cd, OS X 10.10.2_

**Comment by jocelynmallon** [comment]
Just confirming the issue. In this screenshot:  iterm 2 with "NVIM_TUI_ENABLE_TRUE_COLOR=1" set, macvim, vimr, and neovim.app @ 6efa86d7ae22c2901fc9d291e680bcbc4a03e8dd

https://i.imgur.com/nZKTTCB.png

**Comment by rogual** [comment]
I don't know what color space those other apps are using, but I've just committed https://github.com/rogual/neovim-dot-app/commit/b5c87285084e06431c66bb5ac9a79f6b566bb377 which makes Neovim.app interpret colors from Vim as sRGB.

Looks closer to MacVim and Terminal.app to my eye — what do you think?

**Comment by jocelynmallon** [comment]
@rogual looks a lot closer to me too, though sampling color values with a color picker still doesn't return the same values between apps, e.g. for the dark bg (base 16, tomorrow theme) now I get:

Macvim: 1D1F21
Neovim: 1C1F20

**Comment by rogual** [comment]
I wouldn't expect anything to be exact — after all, when we say #1d1f21 in a Vim theme we don't specify a colour space. In fact I'd be surprised if Terminal, iTerm, MacVim and VimR all gave the same colours as each other.

**Comment by kopischke** [comment]
@rogual as noted in my OP, at least MacVim and Terminal.app do, in fact, give the exact same values. Maybe try the *Device RGB* colour space (if that’s available)?

**Comment by rogual** [comment]
Honestly I'm not too bothered about the difference between 1D1F21 and 1C1F20 right now. I'll leave this open in case anyone wants to submit a PR.

**Comment by rogual** [comment]
Disabling `viewDidMoveToWindow (VimView)` fixes this, but brings back the performance issues due to colour space conversion.

Possible fix: recreate bitmap context in this method rather than modifying window's CS.
