### ISSUE TITLE
$PATH variable not initialized properly when using ZSH

### ISSUE THREAD

**Issue by LevitatingOrange** [rogual/neovim-dot-app#84]
Hello,

I have some problems with the `$PATH` variable. When using the app it apparently does not initialize the `$PATH` environment variable; printing it with `:echo $PATH` gives `/usr/bin:/bin:/usr/sbin:/sbin`. This is the system-wide  `$PATH` and not the user-specific one. Starting NeoVim in the command line and printing the path gives the correct result, so it must be a problem with neovim.app 

*NeoVim.app after invoking `:echo $PATH`*
![path](https://cloud.githubusercontent.com/assets/4560504/7465958/eeab2f96-f2da-11e4-9bc9-9871207f70f5.png)

Commit 71066885762d9d84a3b9dce3220256168fdb19a1 should've fixed this but it has apparently not. I tried using the commands used in said commit to get the environment variables. Both invoking zsh, which is my `$SHELL` shell and the default one `/bin/bash` gives the correct environment variables, thus also the `$PATH`. 

Because of this problem, most of NeoMake's build-in markers won't work, because they expect the path to the command line programs (e.g. `rustc`) to be in `$PATH`. This is very hard to change, because one must alter all the markers for all desired filetypes or provide the `$PATH` through other means. 

This is my first created issue ever, so please criticize me for any things I did wrong / could do better the next time.

With kind regards,
levo

**Comment by rogual** [comment]
Hi, thanks for this issue report. I had some trouble following this part:

> Commit 7106688 should've fixed this but it has apparently not. I tried using the commands used in said commit to get the environment variables. Both invoking zsh, which is my $SHELL shell and the default one /bin/bash gives the correct environment variables, thus also the $PATH.

Would you be able to rephrase this?

Also, how are you setting your $PATH? I set mine in `.bash_profile` using `export PATH=blah`; does the issue persist for you if you use Bash and do this? Just trying to ascertain if this issue is zsh-specific.

**Comment by LevitatingOrange** [comment]
I looked at the code in the commit, and it gets the environment variables, if I understand it correctly, by first checking the `$SHELL` variable and using this shell if its set (in my case it is set to `zsh`). When this is not set it uses the `/bin/bash` as a fallback. It invokes the specific shell with the args `-l -c` and `"env"`. (See line 76 of the commit:  `NSArray *args = @[@"-l", @"-c", @"\"env\""];`). If I do exactly the same (executing `/bin/zsh/ -l -c "env"`) I will get the correct environment variables, including the correct `$PATH`. Doing the same with `/bin/bash -l -c "env"` results in the same. I have my `$PATH` set  in `.bashrc`, but this should not be making a difference?!. I just source the `.bashrc` in my zsh file. I tried putting the `$PATH` configuration directly into `.zshrc` but this does not help either.

I will change the app.mm file to only use the /bin/bash and not $SHELL, so we can see if it is indeed a zsh-specific issue. I will report back soon. 

Hope I could make it more clear.

**Comment by LevitatingOrange** [comment]
It is indeed a problem with zsh. After commenting out the use of the $SHELL and instead instantly using `/bin/bash` it works like a charm. Here is what I changed:

```objective-c++
- (void)loadLoginShellEnvironmentVariables
{
//    NSString *shellPath = [[NSProcessInfo processInfo] environment][@"SHELL"]; //<-- change here
    NSString *shellPath = @"/bin/bash";  
    NSDictionary *env = [self environmentFromLoginShell:shellPath];
      if (!env) {
        NSString *shellPath = @"/bin/bash";
        env = [self environmentFromLoginShell:shellPath];
      }

    if (!env) {
        NSLog(@"Couldn't get environment from $SHELL or /bin/bash, defaulting to existing environment.");
    } else {
        [env enumerateKeysAndObjectsUsingBlock:^(NSString *key, NSString *value, BOOL *stop) {
            setenv(key.UTF8String, value.UTF8String, 1);
        }];
    }
}
```

**Comment by LevitatingOrange** [comment]
I tested around a bit and came to the conclusion, when using `/bin/zsh -l -c "env"` that sourcing the `.bashrc` file in the `.zshrc` won't work properly and will not import the whole `$PATH`. The issue still persists though. I put the exports directly into the `.zshrc` file as mentioned above and it still wont work. Even stranger, I copied the code from the commit in a little test project and when I print out the enviroment with NSLog it gives back the correct PATHS.

**Comment by rogual** [comment]
When you run `/bin/zsh -l -c "env"` are you running that from a parent shell where the variables are already set?

**Comment by LevitatingOrange** [comment]
Yes that is correct. But I also used the code from the app.mm and executed it separately in a xcode project. It worked and used the right `$PATH` even with zsh.

**Comment by bfulkers** [comment]
The `-l -c "env"` command will start a login shell and execute the command `env`, which in both bash and zsh would not by default read the corresponding `.zshrc` / `.bashrc` file. @rogual maybe the command should be `-i -c "env"` to set interactive mode?

**Comment by shazow** [comment]
I'm having some weird PATH-related issues in bash, too. I'm sourcing another file from my `~/.bash_profile` which _appends_ to the PATH and other variables. It seems the variables are present when Neovim loads, but the PATH segments are in the wrong order. Can't figure out how this could happen.

When I run nvim, the PATH is correct. `:terminal` from nvim is also correct. When I run Neovim.app, the PATH is wrong, also wrong with `:terminal` inside Neovim.app.

Maybe some debug logging would help trace this issue.

**Comment by brendanjerwin** [comment]
@rogual this one is preventing me from using neovim-dot-app as my daily driver. Anything I can do to help out? I'm not really an OS X developer, but I'd be willing to help as I can.

**Comment by brendanjerwin** [comment]
So, if I understand what is going on, a shell is created and the ENV is slurped out of it and set in the current process with `setenv`, then, later (https://github.com/rogual/neovim-dot-app/blob/95fb342cfdafcc024a23b749e0840543bc8b3c2f/src/vim.cc#L28) an instance of `nvim` is started. I imagine the expectation is that the env from the current process should cascade into `nvim`? 

Where is `process` (from that line I linked) defined? I'd like to see if maybe that is where this is breaking down.

**Comment by rogual** [comment]
https://github.com/rogual/neovim-dot-app/blob/95fb342cfdafcc024a23b749e0840543bc8b3c2f/src/vim.h#L100

**Comment by brendanjerwin** [comment]
OK, so the rubber meets the road here: https://github.com/rogual/neovim-dot-app/blob/95fb342cfdafcc024a23b749e0840543bc8b3c2f/src/process.cc#L27

And, yes, `setenv` should be setting the `environ`: https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man3/setenv.3.html#//apple_ref/doc/man/3/setenv So, this line of reasoning is a bust.

(sry, I'm sure you know this, but at least my spelunking eliminated at least one possible cause...)

I'll figure out how to hack on the code and see if I can get some logging to see what is actually slurped out of the shell here: https://github.com/rogual/neovim-dot-app/blob/95fb342cfdafcc024a23b749e0840543bc8b3c2f/src/app.mm#L32

**Comment by brendanjerwin** [comment]
OK, well I _did_ seem to find a workaround: `launchctl setenv GOPATH $GOPATH` in a terminal. After that, launching `neovim-dot-app` has access to my `GOPATH`. I imagine this just means that the `environ` is being properly set by `launchd`.

**Comment by bfulkers** [comment]
@brendanjerwin, @shazow, and @LevitatingOrange can you confirm how you are starting `neovim-dot-app`?

After doing a little more investigation, I think some of this behavior could be explained by opening from your interactive login shell (usually via `open build/Neovim.app` on the command line) rather than by clicking on the icon.

Also, if someone is willing to post a stripped down `.bash_profile` and `.bashrc` which replicates the problem, that would help in debugging.

**Comment by shazow** [comment]
That's correct, I'm launching it from terminal. This was a while ago, but I remember being able to reproduce it with any changes to PATH (or other variables) in a .bashrc/.bash_profile.

**Comment by brendanjerwin** [comment]
I've been launching from dbl-clicking the icon.

**Comment by bfulkers** [comment]
When neovim-dot-app starts, it inherits whatever environment variables are around and then retrieves the environment variables of a subprocess which runs `$SHELL -l -c env` [here]( https://github.com/rogual/neovim-dot-app/blob/95fb342cfdafcc024a23b749e0840543bc8b3c2f/src/app.mm#L32). Each variable found in this new environment is copied over the existing variable with the same name [here]( https://github.com/rogual/neovim-dot-app/blob/95fb342cfdafcc024a23b749e0840543bc8b3c2f/src/app.mm#L93). The result of this is available to nvim when the process is launched via the `environ` global [here](https://github.com/rogual/neovim-dot-app/blob/95fb342cfdafcc024a23b749e0840543bc8b3c2f/src/process.cc#L27).

A few comments about this:
- If neovim-dot-app is started from a terminal, it takes all the existing terminal environment (including `.profile` and most likely `.bashrc` since you are in interactive mode) and passes that environment to the `$SHELL -l -c env` subprocess, which sources `.profile` again.
- If neovim-dot-app is started by double clicking the icon, it only sources .profile once (and only as a login shell), because the process which is started.

[Here is a great overview of how environment variables (including PATH) can get set in OS X]( http://stackoverflow.com/a/4567308)

Unless there are significant advantages to leaving it this way @rogual, I would suggest that for consistency we should launch the `$SHELL -l -c env` process from an empty environment, which can be done by launching env with the -i option before launching the shell, so `/usr/bin/env -i $SHELL -l -c env`.

This way, everyone would have a predictable environment, determined only by global settings and their .profile. I've made a pull request to do this.

**Comment by rogual** [comment]
Thanks for your comments @bfulkers, they really helped me to finally understand this. I've merged the PR and I hope this issue is solved now. If not, please reopen.

**Comment by yglukhov** [comment]
I'm having torubles with PATH with latest Neovim.app version and zsh. The PATH is not inherited when Neovim.app is started from command line either directly executing the binary or through `open` command. Running nvim from the same shell shows no problems.

**Comment by yglukhov** [comment]
Also I updated `~/.profile` to set the correct `PATH` but still no luck.

**Comment by JesseChavez** [comment]
I'm having the same issue, similar to @yglukhov but I'm using bash

**Comment by bambu** [comment]
@JesseChavez @yglukhov try PR #261

**Comment by alex-ketch** [comment]
I'm using the latest version of neovim-dot-app built from Brew from --HEAD and still encountering this issue. Running macOS Sierra (10.12.1).

I'm running ZSH as well as [NVM](https://github.com/creationix/nvm), so not sure if it's NVM that's causing problems.

If I launch the app from the dock, running `!which stylelint` gives me `stylelint not found`.
Running `gnvim` in terminal and `!which stylelint` gives me `/Users/Ketch/.nvm/versions/node/v6.3.0/bin/stylelint`.

Running `echo $PATH` confirms that there are things missing when starting from the icon.

I'd be more than happy to provide more details to get to the root of this.

Thank again for a great app!
